DROP TABLE IF EXISTS ACCOUNTS ;

CREATE TABLE ACCOUNTS  (
  ACCOUNT VARCHAR(250) PRIMARY KEY,
  BALANCE NUMERIC,
  CREATED DATE,
  USER_ID  NUMERIC);


DROP TABLE IF EXISTS DEBIT_CARDS;
  CREATE TABLE DEBIT_CARDS (
    CARD_NUMBER INT PRIMARY KEY,
    ATM_LIMIT NUMERIC,
    ATM_PERIOD_UNIT VARCHAR(10),
    CONTACTLESS NUMERIC(1),
    ID INT,
    POS_LIMIT NUMERIC,
    POS_PERIOD_UNIT VARCHAR(10),
    SEQUENCE_NUMBER NUMERIC,
    STATUS VARCHAR(10),
    ACCOUNT VARCHAR(15),
    CARD_HOLDER_ID VARCHAR(10)
  );

 DROP TABLE IF EXISTS USER_AGREEMENT;
   CREATE TABLE USER_AGREEMENT (
     ID INT PRIMARY KEY,
     AGREEMENT_ACCOUNT NUMERIC,
     AGREEMENT_TYPE VARCHAR(4),
     USER_ID NUMERIC
   );





